# Generated by Django 2.2.2 on 2019-06-24 18:36

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100)),
                ('sousTitre', models.CharField(max_length=100)),
                ('pays', models.CharField(max_length=100)),
                ('auteur', models.CharField(max_length=42)),
                ('annee', models.CharField(max_length=40)),
                ('contenu', models.TextField(null=True)),
                ('slug', models.SlugField(max_length=100)),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de parution')),
                ('photo', models.ImageField(upload_to='stories/')),
            ],
            options={
                'verbose_name': 'Story',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='Img',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='stories/')),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stories.Story')),
            ],
        ),
    ]
