# Generated by Django 2.2.8 on 2019-12-08 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0002_auto_20191022_1812'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='photo_2',
            field=models.ImageField(null=True, upload_to='stories/'),
        ),
    ]
