# Generated by Django 2.2.2 on 2019-07-28 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100)),
                ('contenu', models.TextField(null=True)),
                ('photo', models.ImageField(upload_to='about/')),
            ],
            options={
                'verbose_name': 'A propos',
            },
        ),
        migrations.CreateModel(
            name='Mentions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categorie', models.CharField(max_length=30)),
                ('contenu', models.TextField(null=True)),
            ],
            options={
                'verbose_name': 'Mentions légales',
            },
        ),
    ]
