# Generated by Django 2.2.2 on 2019-07-28 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annexes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterModelOptions(
            name='mentions',
            options={'verbose_name': 'Mentions légale'},
        ),
    ]
