# Generated by Django 2.2.2 on 2019-07-28 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annexes', '0002_auto_20190728_1119'),
    ]

    operations = [
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categorie', models.CharField(max_length=30)),
                ('contenu', models.TextField(null=True)),
            ],
            options={
                'verbose_name': 'Mentions légale',
            },
        ),
        migrations.DeleteModel(
            name='AboutSettings',
        ),
    ]
