# Generated by Django 2.2.2 on 2019-07-28 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annexes', '0003_auto_20190728_1230'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='policy',
            options={'verbose_name': 'Data policy categorie'},
        ),
        migrations.AlterField(
            model_name='mentions',
            name='categorie',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='policy',
            name='categorie',
            field=models.CharField(max_length=50),
        ),
    ]
