# Generated by Django 2.2.2 on 2019-07-28 18:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('annexes', '0004_auto_20190728_1236'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name': 'A propos - section'},
        ),
        migrations.AlterModelOptions(
            name='mentions',
            options={'verbose_name': 'Mentions légales - catégorie'},
        ),
        migrations.AlterModelOptions(
            name='policy',
            options={'verbose_name': 'Data policy - catégorie'},
        ),
        migrations.AddField(
            model_name='about',
            name='dateCreation',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de création'),
        ),
        migrations.AddField(
            model_name='mentions',
            name='dateCreation',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de création'),
        ),
        migrations.AddField(
            model_name='policy',
            name='dateCreation',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de création'),
        ),
    ]
